const cards = [
  {
    name: "chips",
    type: "food",
    stock: "50",
    picture: "image/chips.jpg",
    row: "1",
  },
  {
    name: "packs of 6 cola",
    type: "food",
    stock: "5",
    picture: "image/cola.jpg",
    row: "1",
  },
  {
    name: "copy paper",
    type: "common items",
    stock: "16",
    picture: "image/paper.jpg",
    row: "1",
  },
  {
    name: "plastic cups",
    type: "food",
    stock: "49",
    picture: "image/cup.jpg",
    row: "1",
  },
  {
    name: "pens",
    type: "common items",
    stock: "8",
    picture: "image/pen.jpg",
    row: "1",
  },
  {
    name: "pencils",
    type: "common items",
    stock: "8",
    picture: "image/pencil.jpg",
    row: "1",
  },
  {
    name: "copy machine",
    type: "common items",
    stock: "3",
    picture: "image/copy.jpg",
    row: "2",
  },
  {
    name: "roasted nuts",
    type: "food",
    stock: "29",
    picture: "image/nuts.jpg",
    row: "2",
  },
  {
    name: "notebooks",
    type: "common items",
    stock: "48",
    picture: "image/notebook.jpg",
    row: "2",
  },
  {
    name: "toy car",
    type: "toy",
    stock: "28",
    picture: "image/car.jpg",
    row: "1",
  },
  {
    name: "lego set",
    type: "toy",
    stock: "42",
    picture: "image/lego.jpg",
    row: "1",
  },
  {
    name: "pack of gummies",
    type: "food",
    stock: "9",
    picture: "image/gummy.jpg",
    row: "2",
  },
  {
    name: "laptop",
    type: "common items",
    stock: "31",
    picture: "image/laptop.jpg",
    row: "2",
  },
  {
    name: "large box of generic candy",
    type: "food",
    stock: "27",
    picture: "image/candy.jpg",
    row: "2",
  },
  {
    name: "superhero transformation belt",
    type: "toy",
    stock: "34",
    picture: "image/belt.jpg",
    row: "1",
  },
  {
    name: "power ranger toy",
    type: "toy",
    stock: "4",
    picture: "image/ranger.png",
    row: "2",
  },
  {
    name: "ultraman figure",
    type: "toy",
    stock: "10",
    picture: "image/dyna.png",
    row: "2",
  },
  {
    name: "pizza plushie",
    type: "toy",
    stock: "20",
    picture: "image/pizza.jpg",
    row: "2",
  },
];
export { cards };
