const cards = [
  {
    name: "paper plates",
    type: "place holder",
    cost: "place holder",
    stock: "50",
    picture: "place holder",
  },
  {
    name: "pizza plush",
    type: "place holder",
    cost: "place holder",
    stock: "5",
    picture: "place holder",
  },
  {
    name: "copy paper",
    type: "place holder",
    cost: "place holder",
    stock: "16",
    picture: "place holder",
  },
  {
    name: "plastic cups",
    type: "place holder",
    cost: "place holder",
    stock: "49",
    picture: "place holder",
  },
  {
    name: "pens",
    type: "place holder",
    cost: "place holder",
    stock: "8",
    picture: "place holder",
  },
  {
    name: "pencils",
    type: "place holder",
    cost: "place holder",
    stock: "8",
    picture: "place holder",
  },
  {
    name: "copy machine",
    type: "place holder",
    cost: "place holder",
    stock: "3",
    picture: "place holder",
  },
  {
    name: "penguin plush",
    type: "place holder",
    cost: "place holder",
    stock: "29",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "48",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "28",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "42",
    picture: "place holder",
  },
  {
    name: "ballons set",
    type: "place holder",
    cost: "place holder",
    stock: "9",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "31",
    picture: "place holder",
  },
  {
    name: "bulk candy",
    type: "place holder",
    cost: "place holder",
    stock: "27",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "34",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "4",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "10",
    picture: "place holder",
  },
  {
    name: "place holder",
    type: "place holder",
    cost: "place holder",
    stock: "20",
    picture: "place holder",
  },
];
export { cards };
